CREATE TABLE USUARIO(
	USU_ID INT IDENTITY,
	USU_NOME VARCHAR (100) NOT NULL,
	USU_EMAIL VARCHAR (100) NOT NULL,
	USU_SENHA VARCHAR (100) NOT NULL

	CONSTRAINT PK_USUARIO PRIMARY KEY (USU_ID)
)

CREATE TABLE PERFIL (
	PER_ID INT IDENTITY,
	PER_NOME VARCHAR (100) NOT NULL

	CONSTRAINT PK_PERFIL PRIMARY KEY (PER_ID) 
)

CREATE TABLE PERFIL_USUARIO(
	PER_ID INT NOT NULL,
	USU_ID INT NOT NULL

	CONSTRAINT PK_PERFIL_USUARIO PRIMARY KEY (PER_ID, USU_ID),
	CONSTRAINT FK_PERFIL_USUARIO_PER_ID FOREIGN KEY (PER_ID)
		REFERENCES PERFIL (PER_ID),
	CONSTRAINT FK_PERFIL_USUARIO_USU_ID FOREIGN KEY (USU_ID)
		REFERENCES USUARIO (USU_ID)
)

INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA) 
	VALUES ('Master', 'master@email.com', 'fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9')

INSERT INTO PERFIL (PER_NOME)
	VALUES ('Master')

INSERT INTO PERFIL_USUARIO (PER_ID, USU_ID)
	VALUES (1, 1)




